# Generated by Django 5.2.5 on 2025-08-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0004_storemenu_dp_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuPricingParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha', models.FloatField(default=0.0)),
                ('beta0', models.FloatField(default=0.0)),
                ('gamma_tilde', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_param', to='stores.storemenu')),
            ],
        ),
    ]
