# Generated by Django 5.2.5 on 2025-08-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPricingParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beta0', models.FloatField(default=0.0)),
                ('alpha', models.FloatField(default=0.0)),
                ('gamma_tilde', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
