# Generated by Django 5.2.5 on 2025-08-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_user_discounted_cost_sum_user_user_image_url_and_more'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_cost', models.PositiveIntegerField()),
                ('reservation_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeslot')),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'unique_together': {('user', 'store_item')},
            },
        ),
    ]
