# Generated by Django 5.2.5 on 2025-08-13 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_image_url', models.TextField(blank=True)),
                ('user_password', models.CharField(default='', max_length=10)),
                ('user_role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('owner', 'Owner')], default='customer', max_length=20)),
                ('user_address', models.CharField(blank=True, max_length=100)),
                ('user_discounted_cost_sum', models.IntegerField(default=0)),
                ('is_dummy', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
