# Generated by Django 5.2.5 on 2025-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_discounted_cost_sum_user_user_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
