# Generated by Django 5.2.5 on 2025-08-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_user_discounted_cost_sum_user_user_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=100)),
                ('store_category', models.CharField(choices=[('카페', '카페'), ('헤어샵', '헤어샵'), ('회의실', '회의실')], max_length=20)),
                ('store_description', models.TextField(blank=True)),
                ('store_address', models.CharField(max_length=200)),
                ('store_image_url', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreMenu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=100)),
                ('menu_image_url', models.TextField(blank=True)),
                ('menu_cost_price', models.PositiveIntegerField()),
                ('menu_price', models.PositiveIntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreSpace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('space_id', models.AutoField(primary_key=True, serialize=False)),
                ('space_name', models.CharField(max_length=100)),
                ('space_image_url', models.TextField(blank=True)),
                ('space_description', models.TextField(blank=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StoreOperatingHour',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operating_hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(choices=[('Mon', '월'), ('Tue', '화'), ('Wed', '수'), ('Thu', '목'), ('Fri', '금'), ('Sat', '토'), ('Sun', '일')], max_length=10)),
                ('open_time', models.PositiveSmallIntegerField()),
                ('close_time', models.PositiveSmallIntegerField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='StoreSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_reservation_date', models.DateField()),
                ('slot_reservation_time', models.PositiveSmallIntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storespace')),
            ],
            options={
                'unique_together': {('space', 'slot_reservation_date', 'slot_reservation_time')},
            },
        ),
        migrations.CreateModel(
            name='StoreMenuSpace',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storemenu')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storespace')),
            ],
            options={
                'unique_together': {('menu', 'space')},
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_reservation_date', models.DateField()),
                ('item_reservation_day', models.CharField(max_length=10)),
                ('item_reservation_time', models.PositiveSmallIntegerField()),
                ('item_stock', models.IntegerField(default=1)),
                ('current_discount_rate', models.FloatField(default=0.0)),
                ('max_discount_rate', models.FloatField(default=0.3)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storemenu')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storespace')),
            ],
            options={
                'unique_together': {('menu', 'space', 'item_reservation_date', 'item_reservation_day', 'item_reservation_time')},
            },
        ),
    ]
