# Generated by Django 5.2.5 on 2025-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storemenu',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storemenuspace',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeoperatinghour',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storeslot',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storespace',
            name='is_dummy',
            field=models.BooleanField(default=False),
        ),
    ]
