# Generated by Django 5.2.5 on 2025-08-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_is_dummy_storeitem_is_dummy_storemenu_is_dummy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_category',
            field=models.CharField(choices=[('미용실', '미용실'), ('네일샵', '네일샵'), ('스터디카페', '스터디카페'), ('PT/필라테스', 'PT/필라테스'), ('스포츠시설', '스포츠시설'), ('연습실/합주실', '연습실/합주실'), ('사진 스튜디오', '사진 스튜디오')], max_length=20),
        ),
    ]
