# Generated by Django 5.2.5 on 2025-08-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_store_store_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemenu',
            name='dp_weight',
            field=models.FloatField(default=0.0),
        ),
    ]
