# Generated by Django 5.2.5 on 2025-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storemenu_dp_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCoordinate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_id', models.PositiveIntegerField()),
                ('store_x', models.FloatField()),
                ('store_y', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
