# Generated by Django 5.2.5 on 2025-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_item_id', models.IntegerField()),
                ('record_reservation_time', models.PositiveSmallIntegerField()),
                ('time_offset_idx', models.IntegerField()),
                ('record_stock', models.IntegerField()),
                ('record_item_price', models.PositiveIntegerField()),
                ('record_discount_rate', models.FloatField()),
            ],
            options={
                'unique_together': {('store_item_id', 'record_reservation_time', 'time_offset_idx')},
            },
        ),
    ]
