# Generated by Django 5.2.5 on 2025-08-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_itemrecord_is_dummy'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecord',
            name='sold',
            field=models.IntegerField(default=1),
        ),
    ]
