# Generated by Django 5.2.5 on 2025-08-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_itemrecord_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrecord',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
    ]
